name: Setup node
description: "Setup pnpm, Node.js."
inputs:
  node-version:
    description: "Version of Node.js using setup."
    default: "20"
    required: false

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml
    - name: Install packages
      shell: sh
      run: pnpm install --frozen-lockfile

