comment:
  status:
    project: off
    patch:
      default:
        target: 60%
  layout: " diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false
