name: build

on:
  push:
    branches: [main]
  pull_request_target:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event_name != 'pull_request_target' }}
        uses: actions/checkout@v3
      - if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup turbo
        uses: ./.github/actions/setup-turbo
        with:
          turbo-cache-key: build
      - name: Run Build
        run: pnpm build
      - name: Upload bundle-analysis (all-@sugarform/core) to Codecov
        run: pnpm dlx @codecov/bundle-analyzer ./packages/core/dist --bundle-name=all-@sugarform/core --upload-token=${{ secrets.CODECOV_TOKEN }}
      - name: Upload bundle-analysis (cjs-@sugarform/core) to Codecov
        run: mkdir ./packages/core/dist-cjs && cp ./packages/core/dist/lib.cjs ./packages/core/dist-cjs && pnpm dlx @codecov/bundle-analyzer ./packages/core/dist-cjs --bundle-name=cjs-@sugarform/core --upload-token=${{ secrets.CODECOV_TOKEN }}
      - name: Upload bundle-analysis (esm-@sugarform/core) to Codecov
        run: mkdir ./packages/core/dist-esm && cp ./packages/core/dist/lib.js ./packages/core/dist-esm && pnpm dlx @codecov/bundle-analyzer ./packages/core/dist-esm --bundle-name=esm-@sugarform/core --upload-token=${{ secrets.CODECOV_TOKEN }}
