name: format-and-lint

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
      - name: Run Prettier
        run: pnpm run format:check

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup turbo
        uses: ./.github/actions/setup-turbo
        with:
          turbo-cache-key: lint
      - name: Run ESLint
        run: pnpm run lint
