name: test

on:
  push:
    branches: [main]
  pull_request_target:

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event_name != 'pull_request_target' }}
        uses: actions/checkout@v3
      - if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup turbo
        uses: ./.github/actions/setup-turbo
        with:
          turbo-cache-key: test
      - name: Run Test
        run: pnpm vitest run --coverage
      - uses: codecov/codecov-action@v5
        with:
          files: ./coverage/coverage-final.json
        env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
