name: test

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup turbo
        uses: ./.github/actions/setup-turbo
        with:
          turbo-cache-key: test
      - name: Run Test
        run: pnpm vitest run --coverage
      - name: Upload test coverages to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage/coverage-final.json
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          files: ./report/junit.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
